config/routes.rb
Rails.application.routes.draw do
  
  resources :formfor
  
  get 'formfor/index'

  get 'formfor/new'

  post 'formfor/create'

  get 'formfor/edit/:post_id' => 'formfor#edit', as: "formfor_edit"

  patch 'formfor/update/:post_id' => 'formfor#update', as: "formfor_update"
  
  delete 'formfor/destroy/:post_id' => 'formfor#destroy', as: "formfor_destroy"
  
  
  
  

  root 'basichtml#index'
  
  get 'basichtml/index'

  get 'basichtml/new'

  post 'basichtml/create'

  

  get 'basichtml/edit/:post_id' => 'basichtml#edit'

  
  get 'basichtml/update/:post_id' => 'basichtml#update'
  
  get 'basichtml/destroy/:post_id' => 'basichtml#destroy'
  
  
  
  post '/basichtml/:post_id_for_you/comments/create' => 'basichtml#commentcreate'
  
  get '/basichtml/:post_id/comments/:comment_id/destroy' => 'basichtml#commentdestroy'
  
  get '/basichtml/:post_id/comments/:comment_id/edit' => 'basichtml#commentedit'
  
  get '/basichtml/:post_id/comments/:comment_id/update' => 'basichtml#commentupdate'
  
  
  
  post '/formfor/:post_id_for_you/comment2s/create' => 'formfor#commentcreate', as: "formfor_ccreate"
  
  get '/formfor/:post_id/comment2s/:comment_id/destroy' => 'formfor#commentdestroy', as: "formfor_cdestroy"
  
  get '/formfor/:post_id/comment2s/:comment_id/edit' => 'formfor#commentedit2', as: "formfor_cedit"
  
  patch '/formfor/:post_id/comment2s/:comment_id/update' => 'formfor#commentupdate', as: "formfor_cupdate"

end

app/models/basichtml.rb
class Basichtml < ActiveRecord::Base
    has_many :comments, dependent: :destroy
end

app/models/comment.rb
class Comment < ActiveRecord::Base
     belongs_to :basichtml
end

app/models/comment2.rb
class Comment2 < ActiveRecord::Base
    belongs_to :formfor
end

app/models/formfor.rb
class Formfor < ActiveRecord::Base
     has_many :comment2s, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception
end

app/controllers/basichtml_controller.rb
class BasichtmlController < ApplicationController
  def index
    @posts = Basichtml.all
  end

  def view
    @post = Basichtml.find(params[:post_id])
    #@comments = Basichtml.find(params[:post_id]).comments.all
  end

  def new
  end
  
  def destroy
    post = Basichtml.find(params[:post_id])
    post.destroy
    
    redirect_to '/basichtml/index'
    
  end

  def edit
    @post = Basichtml.find(params[:post_id])
    
  end
  
  def update
    post = Basichtml.find(params[:post_id])
    post.title=params[:title]
    post.content=params[:content]
    #post.col_category= params[:bo_category]
    post.save
    
    redirect_to '/basichtml/index'
    
  end

  def create
    post =Basichtml.new
    post.title = params[:title]
    post.content= params[:content]
     #post.col_category= params[:bo_category]
    post.save
    
    redirect_to '/basichtml/index'
  end
  
  def commentcreate
        
        @comment = Comment.new
        @comment.basichtml_id= params[:post_id_for_you]
        @comment.content = params[:content]
        @comment.save
        
        redirect_to :back
    end
    
    def commentdestroy
        @x = Basichtml.find(params[:post_id]).comments.find(params[:comment_id])
        @x.destroy
        
        redirect_to :back
    end
    
    def commentedit
        
        @edit_comment=Basichtml.find(params[:post_id]).comments.find(params[:comment_id])
        @g=Basichtml.find(params[:post_id])
        
        
    end
    
    def commentupdate
        
         @update_comment=Basichtml.find(params[:post_id]).comments.find(params[:comment_id])
        @update_comment.content=params[:content]
        @update_comment.save
        
        redirect_to '/basichtml/index'
    end
    
end

app/controllers/formfor_controller.rb
class FormforController < ApplicationController
def index
    @posts = Formfor.all
  end

  

  def new
    @posts = Formfor.new
  end
  
  def destroy
    post = Formfor.find(params[:post_id])
    post.destroy
    
    redirect_to '/formfor/index'
    
  end

  def edit
    @post = Formfor.find(params[:post_id])
    
  end
  
  def update
    post = Formfor.find(params[:post_id])
    post.title=params[:formfor][:title]
    post.content=params[:formfor][:content]
  
    post.save
    
    redirect_to '/formfor/index'
    
  end

  def create
    post =Formfor.new
    post.title = params[:formfor][:title]                #97 p왜 해시를 표현해주는지 설명
    post.content= params[:formfor][:content]
    post.save
    
    redirect_to '/formfor/index'
  end
  
  
  
  
  
  
  def commentcreate
        
        @comment = Comment2.new
        @comment.formfor_id= params[:post_id_for_you]
        @comment.content = params[:content]
        @comment.save
        
        redirect_to :back
    end
    
    def commentdestroy
        @x = Formfor.find(params[:post_id]).comment2s.find(params[:comment_id])
        @x.destroy
        
        redirect_to :back
    end
    
    def commentedit2
        
        @edit_comment=Formfor.find(params[:post_id]).comment2s.find(params[:comment_id])
        @g=Formfor.find(params[:post_id])
        
        
    end
    
    def commentupdate
        
         @update_comment=Formfor.find(params[:post_id]).comment2s.find(params[:comment_id])
        @update_comment.content=params[:comment2][:content]
        @update_comment.save
        
        
        
        redirect_to '/formfor/index'
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/basichtml_helper.rb
module BasichtmlHelper
end

app/helpers/formfor_helper.rb
module FormforHelper
end

app/views/basichtml/commentedit.html.erb
<form action='/basichtml/<%=@g.id%>/comments/<%=@edit_comment.id%>/update' >
        
        
        <textarea name='content'><%=@edit_comment.content%></textarea>
        <input type="submit" value="수정하기"><br>
    </form>

app/views/basichtml/create.html.erb
<h1>Basichtml#create</h1>
<p>Find me in app/views/basichtml/create.html.erb</p>

app/views/basichtml/destroy.html.erb
<h1>Basichtml#destroy</h1>
<p>Find me in app/views/basichtml/destroy.html.erb</p>

app/views/basichtml/edit.html.erb
<h1>Basichtml#edit</h1>
<p>Find me in app/views/basichtml/edit.html.erb</p>

여기는 수정하는 페이지
<form action = '/basichtml/update/<%=@post.id%>'>
    제목:<input type = 'text' name = 'title' value='<%=@post.title%>'><br><br>
    내용:<textarea name = 'content'><%= @post.content %></textarea><br><br>
    
    <input type='submit' value='수정'>
</form>

app/views/basichtml/index.html.erb
<h1>Basichtml#index</h1>
<p>Find me in app/views/basichtml/index.html.erb</p><br>
---------------------------------------------------


<br><br>
게시글 목록 페이지<br>

<%@posts.each do |x|%>
  <br>
  <br>
  제목 : <%=x.title%><br>
  내용 : <%=x.content%><br>  
  <a href='/basichtml/destroy/<%=x.id%>'>삭제</a>
<a href='/basichtml/edit/<%=x.id%>'>수정</a>

  <% x.comments.each do |k| %>

       댓글 내용: <%=k.content %><br>
       <a href="/basichtml/<%=x.id%>/comments/<%=k.id%>/destroy">댓글 삭제</a><br>
       <a href="/basichtml/<%=x.id%>/comments/<%=k.id%>/edit">댓글 수정</a>
    <%end%>
    
    
    
    
    <form action='/basichtml/<%=x.id%>/comments/create' method="post">
        <textarea name='content'></textarea>
        <input type="submit" value="댓글쓰기"><br>
    </form>
  -----------------------------------------
<%end%>

<a href="/basichtml/new">new post</a>

app/views/basichtml/new.html.erb
새 글 쓰는 페이지<br>
<form action = '/basichtml/create' method ='post'>
<%= hidden_field_tag :authenticity_token, form_authenticity_token %>  
    제목:<input type = 'text' name = 'title'><br><br>
    내용:<textarea name = 'content'></textarea><br><br>    
<input type='submit' value='제출'>
</form>

app/views/basichtml/update.html.erb
<h1>Basichtml#update</h1>
<p>Find me in app/views/basichtml/update.html.erb</p>

app/views/formfor/commentedit2.html.erb
<%= form_for @edit_comment, url: formfor_cupdate_path(post_id: @g.id,comment_id: @edit_comment) do |o| %>
    <%=o.text_area :content%><br>
    <%=o.submit %>
<%end %>

app/views/formfor/create.html.erb
<h1>Formfor#create</h1>
<p>Find me in app/views/formfor/create.html.erb</p>

app/views/formfor/destroy.html.erb
<h1>Formfor#destroy</h1>
<p>Find me in app/views/formfor/destroy.html.erb</p>

app/views/formfor/edit.html.erb
<h1>Formfor#edit</h1>
<p>Find me in app/views/formfor/edit.html.erb</p>




<%= form_for @post, url: formfor_update_path(post_id: @post.id) do |f| %>
   제목 : <%=f.text_field :title%><br>
   내용 : <%=f.text_area :content%><br>  
  
  <%= f.submit %>

<%end %>


<%= form_for @post, url: "/formfor/update/#{@post.id}" do |f| %>
   제목 : <%=f.text_field :title%><br>
   내용 : <%=f.text_area :content%><br>  
  
  <%= f.submit %>

<%end %>


<%= form_for @post, url: {action: "update", post_id: @post.id} do |f| %>
   제목 : <%=f.text_field :title%><br>
   내용 : <%=f.text_area :content%><br>  
  
  <%= f.submit %>

<%end %>

app/views/formfor/index.html.erb
<h1>Formfor#index</h1>
<p>Find me in app/views/formfor/index.html.erb</p>

<br><br>
게시글 목록 페이지<br>



<!-----------------바꾸기----------------------------->


<%@posts.each do |x|%>
  <br>
  <br>
  제목 : <%=x.title%><br>
  내용 : <%=x.content%><br>  
  
  <%= link_to '삭제', formfor_destroy_path(post_id: x.id), method: "delete" %><br>
  <%= link_to '수정', formfor_edit_path(post_id: x.id) %><br>
  
   <% x.comment2s.each do |k| %>
   
    댓글 내용: <%=k.content %><br>
    <%= link_to '댓글삭제', formfor_cdestroy_path(post_id: x.id,comment_id: k.id) %><br>
    <%= link_to '댓글수정', formfor_cedit_path(post_id: x.id,comment_id: k.id)%><br>
    
    <%end%>
    
    <%= form_tag ("/formfor/#{x.id}/comment2s/create") do %>
        <%= text_field_tag "content", nil %>
        <input type="submit" value="댓글쓰기"><br>
    <%end%>
  
<%end%>

 <%= link_to '새로운 포스트', formfor_new_path %>

app/views/formfor/new.html.erb
<h1>Formfor#new</h1>
<p>Find me in app/views/formfor/new.html.erb</p>




<%=form_for @posts, url: formfor_create_path do |k| %>
  제목 : <%=k.text_field :title%><br>
  내용 : <%=k.text_area :content%><br>  
  
  <%= k.submit %>
<%end%>

<%=form_for @posts, url: {action: "create"} do |k| %>
  제목 : <%=k.text_field :title%><br>
  내용 : <%=k.text_area :content%><br>  
  
  <%= k.submit %>
<%end%>

<%=form_for @posts, url: "/formfor/create" do |k| %>
  제목 : <%=k.text_field :title%><br>
  내용 : <%=k.text_area :content%><br>  
  
  <%= k.submit %>
<%end%>

 <!-- 
 form_for 메소드로부터 폼 빌더 객체(여기에서는 f)가 생성됩니다.
 폼에서 input 태그를 생성하는 메소드는 폼 빌더 객체 f를 사용해 호출합니다.
 
 -->
 

app/views/formfor/update.html.erb
<h1>Formfor#update</h1>
<p>Find me in app/views/formfor/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>